import { Inter } from "next/font/google";
import "./globals.css";
import { Layout } from "antd";
import HeaderMain from "./components/layouts/header";
import ContentMain from "./components/layouts/content";
import FooterMain from "./components/layouts/footer";

const { Content } = Layout;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout style={{ height: "100%" }}>
          <HeaderMain />
          <ContentMain>{children}</ContentMain>
          <FooterMain />
        </Layout>
      </body>
    </html>
  );
}
